### ISSUE TITLE
explanation regarding mToBeSignedMessage

### ISSUE THREAD

**Issue by asafkin** [Kieun/android-biometricprompt#1]
Can you please explain the mToBeSignedMessage part? i want to update the message when registering but would like to extract this signed message (12345 data) when authenticating. 
Assume no backend here.

Thanks.

**Comment by Kieun** [comment]
Without the help of backend server, you'd better encrypt the data (provided at registration time) and store data somewhere then decrypt the data (after successful authentication).
For this, you need to generate symmetric key (like AES) instead of generating key pair. 
Since a lot of part are similar to previous fingerprint api, you may refer following url.
https://gist.github.com/wyyqyl/b2e8ccf9f796f8d0e107e16eabf46e18
